Repository ResultadosDigitais/hellper, pull requests merged in 2020-08, with the labels that each got.

#114 Update slack app scopes documentation
  docs/CONFIGURING-SLACK.md
Labels: Type: Tech Debt, [Team] Hydra

#112 Notify job
  .gitignore
  Dockerfile
  cmd/notify/main.go
  entrypoint.sh
  internal/notify/channels-notify.go
  internal/notify/custom-notify.go
  internal/notify/notify.go
  internal/notify/report-notify.go
Labels: Type: Enhancement, [Team] Hydra

#118 [Hydra] add cancel route to production
  internal/handler/route.go
Labels: Type: Feature, [Epic] Cancel Incident, [Team] Hydra

#119 add placeholder decription at close incident command team field
  internal/commands/close.go
Labels: Type: Enhancement, [Team] Hydra

#122 [HYDRA] Change max length of incidentTitle and ChannelName in Open Command
  internal/commands/open.go
Labels: Type: Enhancement, [Team] Hydra

#121 Conditional Rules Notify
  go.sum
  internal/notify/channels-notify.go
  internal/notify/notify.go
  internal/reminder/check.go
  internal/reminder/check_last_pin.go
  internal/reminder/check_sla_close.go
  internal/reminder/check_snoozed_until.go
  internal/reminder/check_test.go
Labels: Type: Enhancement, [Team] Hydra

#125 Fix @here mention in Hellper status
  internal/commands/show_status.go
  internal/commands/show_status_test.go
Labels: Type: Bug, [Team] Hydra

#127 Signing Secret
  internal/bot/verify_requests.go
  internal/config/config.go
  internal/handler/close.go
  internal/handler/dates.go
  internal/handler/events.go
  internal/handler/events_test.go
  internal/handler/interactive.go
  internal/handler/open.go
  internal/handler/pause_notify.go
  internal/handler/resolve.go
  internal/handler/route.go
  internal/handler/status.go
Labels: Type: Bug, Type: Tech Debt, [Team] Hydra

#128 Disable goroutine service
  internal/commands/open.go
  internal/handler/route.go
Labels: Type: Enhancement, [Team] Hydra
