Repository ResultadosDigitais/hellper, pull requests merged in 2020-06, with the labels that each got.

#60 Code coverage to user and zap
  internal/commands/util_test.go
  internal/log/zap/zap_test.go
Labels: Type: Enhancement, [Team] Hydra

#65 Hydra insert calendar event
  Dockerfile
  go.sum
  internal/calendar/google_calendar/calendar.go
  internal/calendar/google_calendar/calendar_test.go
  internal/google/calendar.go
  internal/google/calendar_mock.go
  internal/internal.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#70 Insert an event on Google Calendar
  internal/calendar/calendar.go
  internal/calendar/google_calendar/calendar.go
  internal/calendar/google_calendar/calendar_test.go
  internal/google/calendar.go
  internal/google/calendar_mock.go
  internal/model/event.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#72 Private method to create a ConferenceSolutionKey of Google Meet type
  internal/calendar/google_calendar/calendar.go
  internal/calendar/google_calendar/calendar_test.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#69 Calls the function Calendar when a incident has resolved
  README.md
  app.json
  development.env.example
  internal/bot/dialog_submission.go
  internal/commands/resolve.go
  internal/config/config.go
  internal/file_storage/google_drive/file_storage.go
  internal/handler/interactive.go
  internal/handler/route.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#73 Private method to create a CreateConferenceRequest struct
  internal/calendar/google_calendar/calendar.go
  internal/calendar/google_calendar/calendar_test.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#74 Waiting for Postgres to be ready
  .circleci/config.yml
Labels: Type: Bug, [Team] Hydra

#75 Private method to create a ConferenceData struct
  internal/calendar/google_calendar/calendar.go
  internal/calendar/google_calendar/calendar_test.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#76 Post Mortem meeting message
  internal/bot/client_mock.go
  internal/calendar/calendar_mock.go
  internal/calendar/google_calendar/calendar.go
  internal/commands/dates.go
  internal/commands/dates_test.go
  internal/commands/resolve.go
  internal/commands/resolve_test.go
  internal/commands/show_status.go
  internal/handler/interactive.go
  internal/model/event.go
  internal/model/repository_mock.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#80 Adding getUsersInConversation
  internal/bot/client.go
  internal/bot/client_mock.go
  internal/commands/user.go
Labels: Type: Enhancement, [Team] Hydra

#82 Hydra conditional sla
  README.md
  app.json
  development.env.example
  internal/bot/data.go
  internal/commands/reminder.go
  internal/config/config.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra
