Repository ResultadosDigitais/hellper, pull requests merged in 2020-05, with the labels that each got.

#45 Change Google Cred env name
  README.md
  app.json
  docs/CONFIGURING-GOOGLE.md
  internal/config/config.go
  internal/file_storage/google_drive/file_storage.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#49 Create HELLPER_GOOGLE_CALENDAR_TOKEN env
  app.json
  development.env.example
  internal/config/config.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#48 Create section about Google Calendar API
  README.md
  docs/CONFIGURING-GOOGLE.md
Labels: Type: Documentation, [Epic] Post-mortem due date, [Team] Hydra

#46 Create google auth package
  go.sum
  internal/file_storage/google_drive/file_storage.go
  internal/google_auth/auth.go
Labels: Type: Enhancement, [Epic] Post-mortem due date, [Team] Hydra

#52 Create env HELLPER_GOOGLE_CALENDAR_ID
  app.json
  development.env.example
  internal/config/config.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#53 Create env HELLPER_POSTMORTEM_GAP_DAYS
  README.md
  app.json
  development.env.example
  internal/config/config.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#55 Insert the incident's commander email on database
  internal/commands/open.go
  internal/model/incident.go
  internal/model/sql/postgres/repository.go
  internal/model/sql/postgres/schema/hellper.sql
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#54 Create calendar package
  internal/calendar/calendar.go
  internal/calendar/calendar_mock.go
  internal/calendar/google_calendar/calendar.go
  internal/calendar/google_calendar/calendar_test.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#56 Create user.go in the command package
  internal/bot/client.go
  internal/bot/client_mock.go
  internal/commands/open.go
  internal/commands/show_status.go
  internal/commands/user.go
  internal/commands/user_test.go
  internal/model/user.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#58 Create Event struct
  internal/calendar/google_calendar/calendar.go
  internal/calendar/google_calendar/calendar_test.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#57 Initialize calendar package
  internal/calendar/google_calendar/calendar.go
  internal/calendar/google_calendar/calendar_test.go
  internal/google_auth/auth_mock.go
  internal/handler/route.go
  internal/internal.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra
