Repository ResultadosDigitais/hellper, pull requests merged in 2020-07, with the labels that each got.

#83 Create function to get users emails from a conversation in Slack
  internal/commands/user.go
Labels: Type: Feature, [Epic] Post-mortem due date, [Team] Hydra

#84 Insert the column snoozed_at on database
  internal/model/incident.go
  internal/model/sql/postgres/repository.go
  internal/model/sql/postgres/schema/hellper.sql
Labels: Type: Feature, [Epic] Post-Mortem Pause Incident, [Team] Hydra

#85 Appending event attendees
  internal/calendar/google_calendar/calendar.go
  internal/commands/resolve.go
  internal/commands/resolve_test.go
Labels: Type: Feature, [Team] Hydra

#86 Show pause notify
  internal/commands/pause_notify.go
  internal/commands/util.go
  internal/handler/interactive.go
  internal/handler/pause_notify.go
  internal/handler/route.go
Labels: Type: Feature, [Team] Hydra

#87 Save pause notify
  internal/bot/dialog_submission.go
  internal/commands/pause_notify.go
  internal/model/repository.go
  internal/model/repository_mock.go
  internal/model/sql/postgres/repository.go
Labels: Type: Feature, [Team] Hydra

#89 Changed the select limit to 100
  internal/model/sql/postgres/repository.go
Labels: Type: Bug, [Team] Hydra

#90 Pinning the reason in the pause command
  internal/commands/pause_notify.go
Labels: Type: Feature, [Team] Hydra

#92 Conversion API migration
  go.sum
  internal/bot/client.go
  internal/bot/client_mock.go
  internal/commands/cancel.go
  internal/commands/close.go
  internal/commands/commands_test.go
  internal/commands/open.go
  internal/handler/events_test.go
Labels: Type: Tech Debt, [Team] Hydra

#91 Conditional pause
  internal/commands/pause_notify.go
  internal/commands/reminder.go
  internal/model/incident.go
  internal/model/sql/postgres/repository.go
Labels: Type: Feature, [Team] Hydra

#93 Pause command documentation
  README.md
  docs/CONFIGURING-SLACK.md
Labels: Type: Documentation, [Team] Hydra

#97 Hydra add incident commander inc topic
  internal/bot/client.go
  internal/bot/client_mock.go
  internal/commands/open.go
Labels: Type: Bug, [Team] Hydra, slack

#99 change column snoozed_at name to snoozed_until in PostgreSQL
  internal/commands/pause_notify.go
  internal/commands/reminder.go
  internal/model/incident.go
  internal/model/sql/postgres/repository.go
  internal/model/sql/postgres/schema/hellper.sql
Labels: Type: Enhancement, [Team] Hydra

#100 Create env HELLPER_NOTIFY_ON_CANCEL
  README.md
  app.json
  internal/config/config.go
Labels: Type: Feature, [Epic] Cancel Incident, [Team] Hydra

#104 Fix pinned message for status
  internal/commands/cancel.go
  internal/commands/close.go
  internal/commands/open.go
  internal/commands/postmortem.go
  internal/commands/resolve.go
  internal/commands/show_status.go
Labels: Type: Bug

#106 Fix Last Pin Error
  internal/bot/data.go
  internal/bot/data_test.go
  internal/commands/reminder.go
Labels: Type: Bug, [Team] Hydra, slack

#109 Cancel command tests
  internal/commands/cancel.go
  internal/commands/cancel_test.go
  internal/commands/dates_test.go
  internal/commands/resolve_test.go
  internal/handler/interactive.go
  internal/model/repository_mock.go
Labels: [Epic] Cancel Incident, [Team] Hydra

#111 Hydra add incident id to comms
  internal/commands/cancel.go
  internal/commands/cancel_test.go
  internal/commands/close.go
  internal/commands/open.go
  internal/commands/postmortem.go
  internal/commands/resolve.go
  internal/commands/resolve_test.go
  internal/commands/util.go
  internal/handler/cancel.go
  internal/handler/close.go
  internal/handler/open.go
  internal/handler/resolve.go
Labels: Type: Enhancement, [Team] Hydra
